/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package www.fourgenius.www.sp;

import java.util.Arrays;
import java.util.Vector;
import javax.swing.ImageIcon;
import static www.fourgenius.www.sp.Jp_MainMenu.lb_load_email;
import static www.fourgenius.www.sp.Jp_MainMenu.lb_load_id;

/**
 *
 * @author deepalsuranga
 */
public class Jf_MainFrame extends javax.swing.JFrame {

    public static String Emailget;
    /*
     * Creates new form jf_MainFrame
     */

    public Jf_MainFrame() {
        initComponents();
        firstLoad();
        Emailget = lb_load_MainEmail.getText();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lb_load_MainEmail = new javax.swing.JLabel();
        lb_load_home = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel2.setBackground(new java.awt.Color(31, 31, 31));
        jPanel2.setMaximumSize(new java.awt.Dimension(1366, 30));
        jPanel2.setMinimumSize(new java.awt.Dimension(1366, 30));

        jPanel4.setBackground(new java.awt.Color(255, 87, 34));

        lb_load_MainEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_load_MainEmail.setForeground(new java.awt.Color(255, 255, 255));
        lb_load_MainEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_load_MainEmail.setText("Load Email Address");
        lb_load_MainEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_load_MainEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_load_MainEmailMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_load_MainEmailMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_load_MainEmailMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(lb_load_MainEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_load_MainEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lb_load_home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_load_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/imagess/ic_home_white_24dp_1x.png"))); // NOI18N
        lb_load_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_load_homeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_load_homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_load_homeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(lb_load_home, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1061, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lb_load_home, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        mainPanel.setBackground(new java.awt.Color(97, 97, 97));
        mainPanel.setMaximumSize(new java.awt.Dimension(1366, 732));
        mainPanel.setMinimumSize(new java.awt.Dimension(1366, 732));
        mainPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1366, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, "card2");

        setSize(new java.awt.Dimension(1366, 768));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lb_load_homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_load_homeMouseEntered

        lb_load_home.setIcon(new ImageIcon("src\\src\\imagess\\Home-24-rollover.png"));
        lb_load_home.setToolTipText("Home");

    }//GEN-LAST:event_lb_load_homeMouseEntered

    private void lb_load_homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_load_homeMouseExited

        lb_load_home.setIcon(new ImageIcon("src\\src\\imagess\\ic_home_white_24dp_1x.png"));

    }//GEN-LAST:event_lb_load_homeMouseExited

    private void lb_load_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_load_homeMouseClicked

        firstLoad();

    }//GEN-LAST:event_lb_load_homeMouseClicked

    private void lb_load_MainEmailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_load_MainEmailMouseEntered

        lb_load_MainEmail.setText("Logout");

    }//GEN-LAST:event_lb_load_MainEmailMouseEntered

    private void lb_load_MainEmailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_load_MainEmailMouseExited

        lb_load_MainEmail.setText(Emailget);

    }//GEN-LAST:event_lb_load_MainEmailMouseExited

    private void lb_load_MainEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_load_MainEmailMouseClicked

        student_login login = new student_login();
        login.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_lb_load_MainEmailMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jf_MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jf_MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jf_MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jf_MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Jf_MainFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    public static javax.swing.JLabel lb_load_MainEmail;
    private javax.swing.JLabel lb_load_home;
    public static javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables

    static void firstLoad() {
        Jp_MainMenu PanelA = new Jp_MainMenu();
        if (PanelA == null) {
            PanelA = new Jp_MainMenu();
            mainPanel.removeAll();
            mainPanel.repaint();
            mainPanel.revalidate();
            mainPanel.add(PanelA);
            mainPanel.repaint();
            mainPanel.revalidate();
        } else {
            mainPanel.removeAll();
            mainPanel.repaint();
            mainPanel.revalidate();
            mainPanel.add(PanelA);
            mainPanel.repaint();
            mainPanel.revalidate();
        }
    }

    public static void loadEmailM(String load_email, String load_ID) {
        Emailget = load_email;
        lb_load_MainEmail.setText(load_email);

    }
    /*
     
     */
}
