/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package www.fourgenius.www.sp;

import FourGenius.MC_JavaDataBaseConnection;
import java.awt.Color;
import java.awt.Event;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.border.Border;
import www.fourgenius.www.foegetPassword.Jf_forgetPassword;

/**
 *
 * @author deepalsuranga
 */
public class student_login extends javax.swing.JFrame {

    /**
     * Creates new form student_login
     */
    public student_login() {
        initComponents();

        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
        }
        tf_user_email.grabFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tf_user_email = new javax.swing.JTextField();
        pf_user_password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lb_foegetPassword = new javax.swing.JLabel();
        lb_non_password = new javax.swing.JLabel();
        lb_non_email = new javax.swing.JLabel();
        login_ongs = new javax.swing.JLabel();
        backdground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(0, 131, 143));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(31, 31, 31));
        jPanel1.setMaximumSize(new java.awt.Dimension(1366, 40));
        jPanel1.setMinimumSize(new java.awt.Dimension(1366, 40));
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 40));

        jPanel3.setBackground(new java.awt.Color(255, 87, 34));
        jPanel3.setLayout(new java.awt.CardLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("X");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
        });
        jPanel3.add(jLabel5, "card2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 1336, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        tf_user_email.setBackground(new java.awt.Color(0, 153, 153));
        tf_user_email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf_user_email.setForeground(new java.awt.Color(255, 255, 255));
        tf_user_email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_user_email.setBorder(null);
        tf_user_email.setMaximumSize(new java.awt.Dimension(205, 30));
        tf_user_email.setMinimumSize(new java.awt.Dimension(205, 30));
        tf_user_email.setOpaque(false);
        tf_user_email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tf_user_emailMouseEntered(evt);
            }
        });
        tf_user_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_user_emailKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_user_emailKeyTyped(evt);
            }
        });
        jPanel2.add(tf_user_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 638, 205, 30));

        pf_user_password.setBackground(new java.awt.Color(0, 153, 153));
        pf_user_password.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pf_user_password.setForeground(new java.awt.Color(255, 255, 255));
        pf_user_password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pf_user_password.setBorder(null);
        pf_user_password.setMaximumSize(new java.awt.Dimension(195, 30));
        pf_user_password.setMinimumSize(new java.awt.Dimension(195, 30));
        pf_user_password.setOpaque(false);
        pf_user_password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pf_user_passwordMouseEntered(evt);
            }
        });
        pf_user_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pf_user_passwordKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pf_user_passwordKeyTyped(evt);
            }
        });
        jPanel2.add(pf_user_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 640, 195, 30));

        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 640, 40, 30));

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 640, 30, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Student Portal System");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 520, 250, 50));

        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel4MouseReleased(evt);
            }
        });
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(832, 634, 142, 41));
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 530, 50, 50));

        lb_foegetPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_foegetPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/images/img_login/Help-32.png"))); // NOI18N
        lb_foegetPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_foegetPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_foegetPasswordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_foegetPasswordMouseEntered(evt);
            }
        });
        jPanel2.add(lb_foegetPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 630, 30, 40));
        jPanel2.add(lb_non_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 620, 230, 10));
        jPanel2.add(lb_non_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 620, 250, 10));

        login_ongs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_ongs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/images/img_login/login.png"))); // NOI18N
        login_ongs.setOpaque(true);
        jPanel2.add(login_ongs, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 620, 700, 70));

        backdground.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backdground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/images/img_login/login_background.jpg"))); // NOI18N
        backdground.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        backdground.setMaximumSize(new java.awt.Dimension(1366, 768));
        backdground.setMinimumSize(new java.awt.Dimension(1366, 768));
        backdground.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel2.add(backdground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1366, 768));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tf_user_emailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_user_emailKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            pf_user_password.grabFocus();
        }

    }//GEN-LAST:event_tf_user_emailKeyPressed

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered

        jLabel1.setToolTipText("Enter Your Email");

    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked


    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked


    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered

        jLabel2.setToolTipText("Enter Your Password");

    }//GEN-LAST:event_jLabel2MouseEntered
    Border createLineBorder = BorderFactory.createLineBorder(Color.WHITE);
    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered

        jLabel4.setBorder(createLineBorder);

    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseReleased

        jLabel4.setBorder(null);

    }//GEN-LAST:event_jLabel4MouseReleased

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited

        jLabel4.setBorder(null);

    }//GEN-LAST:event_jLabel4MouseExited
    Border createLineBorder2 = BorderFactory.createLineBorder(Color.GREEN);
    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        jLabel4.setBorder(createLineBorder2);
        if (!tf_user_email.getText().isEmpty()) {
            String EMAIL_REGEX = "^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";
            String email1 = tf_user_email.getText();
            Boolean result = email1.matches(EMAIL_REGEX);
            if (result) {

                login_method();
            } else {
                JOptionPane.showMessageDialog(this, "Please Enter Valid Email.", "WARNING!", JOptionPane.WARNING_MESSAGE);
                tf_user_email.grabFocus();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please Notice Email is Empty. Email is Required for Login Student Portal", "WARNING!", JOptionPane.WARNING_MESSAGE);

        }


    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed

        jLabel4.setBorder(createLineBorder2);

    }//GEN-LAST:event_jLabel4MousePressed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked

        int i = JOptionPane.showConfirmDialog(this, "Are you Sure Quit This System", "Confrom", JOptionPane.YES_NO_OPTION);
        if (i == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered

        jLabel5.setToolTipText("Close");

    }//GEN-LAST:event_jLabel5MouseEntered

    ResultSet rs;
    private void pf_user_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pf_user_passwordKeyPressed
//        try {
//            String status_Q = "SELECT * FROM stu_user_info WHERE stu_user_info_status='" + 1 + "'".trim();
//            rs = MC_JavaDataBaseConnection.myConnection().createStatement().executeQuery(status_Q);
//            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
//                try {
//                    if (rs.next()) {
//                        empty_is_Password();
//                        empty_is_Username();
//                        login_method();
//                    } else {
//                        JOptionPane.showMessageDialog(this, "You Haven't Access The Student Portal System");
//
//                    }
//
//                } catch (SQLException ex) {
//                    Logger.getLogger(student_login.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//        } catch (SQLException ex) {
//            Logger.getLogger(student_login.class.getName()).log(Level.SEVERE, null, ex);
//        }

        if (evt.getKeyCode() == Event.ENTER) {
            jLabel4.setBorder(createLineBorder2);

            login_method();
        }

    }//GEN-LAST:event_pf_user_passwordKeyPressed

    private void tf_user_emailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_user_emailKeyTyped

        if (tf_user_email.getText().length() >= 100) {
            JOptionPane.showMessageDialog(this, "You enterd more than 100 letters!");
            evt.consume();
        }

    }//GEN-LAST:event_tf_user_emailKeyTyped

    private void pf_user_passwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pf_user_passwordKeyTyped

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            login_method();
        }

    }//GEN-LAST:event_pf_user_passwordKeyTyped

    private void lb_foegetPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_foegetPasswordMouseClicked
        if (!tf_user_email.getText().isEmpty()) {
            String EMAIL_REGEX = "^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";
            String email1 = tf_user_email.getText();
            Boolean result = email1.matches(EMAIL_REGEX);
            if (result) {

                Jf_forgetPassword jf_forgetPassword = new Jf_forgetPassword();
                
                    jf_forgetPassword.loadEmail(email1.toLowerCase().trim());
                    jf_forgetPassword.setVisible(true);
                    jf_forgetPassword.setAlwaysOnTop(true);
                
                    
                
            } else {
                JOptionPane.showMessageDialog(this, "Please Enter Valid Email.", "WARNING!", JOptionPane.WARNING_MESSAGE);
                tf_user_email.grabFocus();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please Notice Email is Empty!\n\tEmail is Required", "WARNING!", JOptionPane.WARNING_MESSAGE);

        }


    }//GEN-LAST:event_lb_foegetPasswordMouseClicked

    private void lb_foegetPasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_foegetPasswordMouseEntered

        lb_foegetPassword.setToolTipText("Forget Password!");
        
    }//GEN-LAST:event_lb_foegetPasswordMouseEntered

    private void tf_user_emailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_user_emailMouseEntered

        jLabel1.setToolTipText("Enter Your Email");
        
    }//GEN-LAST:event_tf_user_emailMouseEntered

    private void pf_user_passwordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pf_user_passwordMouseEntered

        jLabel2.setToolTipText("Enter Your Password");
        
    }//GEN-LAST:event_pf_user_passwordMouseEntered

    /*
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(student_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(student_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(student_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(student_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new student_login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backdground;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lb_foegetPassword;
    private javax.swing.JLabel lb_non_email;
    private javax.swing.JLabel lb_non_password;
    private javax.swing.JLabel login_ongs;
    private javax.swing.JPasswordField pf_user_password;
    private javax.swing.JTextField tf_user_email;
    // End of variables declaration//GEN-END:variables
    static ResultSet resultSet;
    static ResultSet resultSet2;
    String student_login_QU, student_login_QP;
    String userEmail, UserPassword;
    Jf_loading loading = new Jf_loading();

    public void login_method() {

        //loading.setVisible(true);
        //loading.setAlwaysOnTop(true);
        try {
            UserPassword = new String(pf_user_password.getPassword()).trim();
            userEmail = tf_user_email.getText().trim().toLowerCase();
            student_login_QU = "SELECT * FROM stu_user_info WHERE stu_user_info_email='" + userEmail + "'".trim();
            student_login_QP = "SELECT * FROM stu_user_info WHERE stu_user_info_password='" + UserPassword + "'".trim();

            resultSet = MC_JavaDataBaseConnection.myConnection().createStatement().executeQuery(student_login_QU);
            resultSet2 = MC_JavaDataBaseConnection.myConnection().createStatement().executeQuery(student_login_QP);

            System.out.println("password is " + UserPassword);

            if (!tf_user_email.getText().isEmpty() & !pf_user_password.getPassword().toString().isEmpty()) {

                if (resultSet.next()) {
                    if (resultSet2.next()) {
                        Jf_MainFrame mainFrame = new Jf_MainFrame();
                        mainFrame.setVisible(true);
                        Jp_MainMenu.loadEmail(userEmail, userEmail);

                        this.dispose();
                    } else {
                        //tf_user_email.setText(null);
                        pf_user_password.selectAll();
                        JOptionPane.showMessageDialog(this, "Your password incorrect");
                        pf_user_password.grabFocus();
                    }

                } else {
                    tf_user_email.selectAll();
                    //tf_user_email.setText(null);
                    //pf_user_password.setText(null);
                    JOptionPane.showMessageDialog(this, "Your email incorrect");
                    tf_user_email.grabFocus();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Email & password Filed is empty!");
                tf_user_email.grabFocus();
            }
//            try {
//
//                new Thread(new Runnable() {
//
//                    public void run() {
//                        try {
//                            for (int i = 0; i < 101; i++) {
//                                if (i == 100) {
////                            Jf_MainFrame ul = new Jf_MainFrame();
////                            ul.setVisible(true);
//                                    loading.dispose();
//                                }
//                                student_login.this.dispose();
//                                Thread.sleep(50);
//                            }
//                        } catch (Exception e) {
//                        }
//                    }
//                }).start();
//
//            } catch (Exception e) {
//            }
            resultSet.close();
            MC_JavaDataBaseConnection.myConnection().close();

        } catch (SQLException ex) {
            Logger.getLogger(student_login.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void empty_is_Username() {
        if (tf_user_email.getText().isEmpty()) {
            lb_non_email.setText("Requred email filed!");
            tf_user_email.grabFocus();
        }
    }

    public void empty_is_Password() {
        if (pf_user_password.getPassword().toString().isEmpty()) {
            lb_non_password.setText("Requred password field!");
            pf_user_password.grabFocus();
        }
    }
}
